export const data = [
  {
    name: 'saodaye',
    url: 'https://saodaye.com/index.php',
    item: '.post-item',
    title: '.entry-title a',
    link: '.entry-title a',
    date: '.entry-date',
  },
  {
    name: '缙哥哥',
    url: 'https://www.dujin.org/',
    item: '.excerpt',
    title: 'header h2 a',
    link: 'header h2 a',
    date: '.meta time',
  },
  {
    name: '果核剥壳',
    url: 'https://www.ghpym.com/',
    item: '.item',
    title: '.item-title a',
    link: '.item-title a',
    date: '.date',
  },
  {
    name: 'WINOS',
    url: 'https://www.winos.me/',
    item: 'article.post',
    title: '.entry-title a',
    link: '.entry-title a',
    date: '.date',
  },
  {
    name: '蓝点网',
    url: 'https://www.landiannews.com/',
    item: '.ajaxpost',
    title: 'h2 a',
    link: 'h2 a',
    date: '.date',
  },
  {
    name: '汉化博客',
    url: 'http://www.th-sjy.com/',
    item: 'article.excerpt',
    title: 'header h2 a',
    link: 'header h2 a',
    date: '',
  },
  // {
  //   name: 'saodaye',
  //   url: 'https://saodaye.com/index.php',
  //   item: '.post-item',
  //   title: '.entry-title a',
  //   link: '.entry-title a',
  //   date: '.entry-date',
  // },
]
