export const data = [
  {
    name: 'saodaye',
    url: 'https://saodaye.com/index.php',
    searchUrl: 'https://saodaye.com/?s=',
    item: '.post-item',
    title: '.entry-title a',
    link: '.entry-title a',
    date: '.entry-date',
  },
  {
    name: '缙哥哥',
    url: 'https://www.dujin.org/',
    searchUrl: 'https://www.dujin.org/?s=',
    item: '.excerpt',
    title: 'header h2 a',
    link: 'header h2 a',
    date: '.meta time',
  },
  {
    name: '果核剥壳',
    url: 'https://www.ghpym.com/',
    searchUrl: 'https://www.ghpym.com/?s=',
    item: '.item',
    title: '.item-title a',
    link: '.item-title a',
    date: '.date',
  },
  {
    name: 'WINOS',
    url: 'https://www.winos.me/',
    searchUrl: 'https://www.winos.me/?s=',
    item: 'article.post',
    title: '.entry-title a',
    link: '.entry-title a',
    date: '.date',
    searchItem: '.search-page > .entry-title',
    searchTitle: 'a',
    searchLink: 'a',
    searchDate: 'a',
  },
  {
    name: '蓝点网',
    url: 'https://www.landiannews.com/',
    searchUrl: 'https://www.landiannews.com/?post_type=post&s=',
    item: '.ajaxpost',
    title: 'h2 a',
    link: 'h2 a',
    date: '.date',
  },
  {
    name: '爱免费吧',
    url: 'https://www.imf8.cn/',
    searchUrl: 'https://www.imf8.cn/search.php?q=',
    item: '.auto-list',
    title: 'h3 a',
    link: 'h3 a',
    date: '.mu-ml-clock',
  },
  {
    name: '软件SOS',
    url: 'https://www.rjsos.com/list/newest',
    searchUrl: 'https://www.rjsos.com/search?s=',
    item: '.item-list li',
    title: '.txt1 a',
    link: '.txt1 a',
    date: '.author',
  },
]
